vim.opts.backup = false
vim.opts.clipboard = "unnamedplus"
vim.opts.-- cmdheight = 2
vim.opts.completeopt = { "menu", "menuone", "noselect" }
vim.opts.conceallevel = 0
vim.opts.--  fileencoding = "uft-8"
vim.opts.ignorecase = true
vim.opts.mouse = 'a'
vim.opts.pumheight = 10
vim.opts.showmatch = true
vim.opts.showmode = false
vim.opts.showtabline = 1
vim.opts.smartcase = true
vim.opts.smartindent = true
vim.opts.foldlevelstart = 99
vim.opts.splitbelow = true
vim.opts.splitright = true
vim.opts.swapfile = false
vim.opts.termguicolors = true
vim.opts.timeoutlen = 1000
vim.opts.undofile = true
vim.opts.updatetime = 300
vim.opts.writebackup = false
vim.opts.expandtab = true
vim.opts.shiftwidth = 2
vim.opts.tabstop = 2
vim.opts.cursorline = true
vim.opts.number = true
vim.opts.relativenumber = false
vim.opts.numberwidth = 4
vim.opts.signcolumn = "auto"
vim.opts.wrap = false
vim.opts.scrolloff = 8
vim.opts.sidescrolloff = 8
vim.opts.virtualedit = "onemore"
