* Emacs Installation
** using scoop
#+begin_src shell
  scoop bucket add kiennq-scoop https://github.com/kiennq/scoop-misc
  scoop install emacs-k
#+end_src

* Start emacs server on startup
** Windows
(taken from [[https://www.emacswiki.org/emacs/EmacsMsWindowsIntegration]])

Open Windows Explorer with `Win+E’ and navigate to `shell:startup’. Create a new
file `StartEmacsServer.bat’ using the right click context menu. Right click this
new file, select “Edit”, and insert:

#+begin_src shell
rem Sets HOME for current shell if you haven't set HOME environment variable already
set HOME=%APPDATA%

del /q %HOME%\.emacs.d\server\*
C:\path\to\emacs\bin\runemacs.exe --daemon --chdir %HOME%
#+end_src

‘rem’ is the Windows batch keyword for comments. This script sets a HOME
environment variable for the current cmd process, meaning it will not exist
beyond the running of the script. It then deletes the folder which contains
Emacs server information. ‘/q’ means “quiet”; the user is not prompted whether
to delete. You can use double quotes to provide single quotes around the path,
in case it contains spaces. Finally, `runemacs.exe’ is called with the
‘--daemon’ flag, starting a background instance. If you want to modify/debug
this script, put ‘pause’ at the end and the prompt will remain open.

Double clicking the script will start a new Emacs daemon. To create a new frame,
make a shortcut for `emacsclientw.exe’. Right click on the shortcut and select
“Properties”. Set the “Target” as:

#+begin_src shell
C:\path\to\emacs\bin\emacsclientw.exe -create-frame
#+end_src shell

This tells `emacsclientw.exe’ to create a new frame within the Emacs daemon
process. If it fails, no alternative editor is to be opened. Use this shortcut
as the main entry point to Emacs.
