local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>f', function() end, {desc = '+Find'})
vim.keymap.set('n', '<leader>ff', builtin.find_files, {desc='files'})
vim.keymap.set('n', '<C-p>', builtin.git_files, {})
vim.keymap.set('n', '<leader>fg', function()
		  builtin.grep_string({search = vim.fn.input("Grep > ")})
end, {desc = "grep"})
