(defvar lm/leader-map (make-sparse-keymap) "Keymap for \"leader key\" shortcuts")
(unless (boundp 'lm/evil-mode)
  (keymap-set global-map "C-ò" 'lm/leader-mao))
(keymap-set lm/leader-map "SPC" 'execute-extended-command)
(defvar lm/leader-map-buffer (make-sparse-keymap)
  "sub-keymap for buffer operations")
(keymap-set lm/leader-map "b" `("+Buffer" . ,lm/leader-map-buffer))
(keymap-set lm/leader-map-buffer "d" 'kill-this-buffer)
(keymap-set lm/leader-map-buffer "s" 'save-buffer)
(keymap-set lm/leader-map-buffer "l" 'switch-to-buffer)
(keymap-set lm/leader-map-buffer "L" 'list-buffers)
(defvar lm/leader-map-quit (make-sparse-keymap)
  "sub-keymap for quit operations")
(keymap-set lm/leader-map "q" `("+Quit" . ,lm/leader-map-quit))
(keymap-set lm/leader-map-quit "q" 'save-buffers-kill-terminal)
(defvar lm/leader-map-find (make-sparse-keymap)
  "sub-keymap for finding operations")
(keymap-set lm/leader-map "f" `("+Find" . ,lm/leader-map-find))
(keymap-set lm/leader-map-find "f" 'project-find-file)
(keymap-set lm/leader-map-find "s" 'search-forward)
(keymap-set lm/leader-map-find "b" 'search-backward)
(keymap-set lm/leader-map-find "r" 'query-replace)
(defvar lm/leader-map-appearence (make-sparse-keymap)
  "sub-keymap for customizing appearence operations")
(keymap-set lm/leader-map "a" `("+Appearence" . ,lm/leader-map-appearence))
(keymap-set lm/leader-map-appearence "c" 'customize-themes)
(keymap-set lm/leader-map-appearence "t" 'toggle-theme)
(keymap-set lm/leader-map-appearence "m" 'menu-bar-mode)
(defvar lm/leader-map-config (make-sparse-keymap)
  "sub-keymap for customizing configuration operations")
(keymap-set lm/leader-map "c" `("+Configuration" . ,lm/leader-map-config))
(keymap-set lm/leader-map-config "c" 'lm/open-literate-config)
(keymap-set lm/leader-map-config "r" 'lm/reload-config)
(defvar lm/leader-map-project (make-sparse-keymap)
  "sub-keymap for customizing project operations")
(keymap-set lm/leader-map "p" `("+Project" . ,lm/leader-map-project))
(keymap-set lm/leader-map-project "c" 'lm/run-wezterm)
(keymap-set lm/leader-map-project "p" 'project-asyn-shell-command)
(defvar lm/leader-map-special-chars (make-sparse-keymap)
  "sub-keymap for inserting special characters")
(keymap-set lm/leader-map "i" `("+Insert" . ,lm/leader-map-special-chars))
(keymap-set lm/leader-map-special-chars "t" 'lm/insert-tilde)
(keymap-set lm/leader-map-special-chars "g" 'lm/insert-grave-accent)
(defvar lm/leader-map-tools (make-sparse-keymap)
  "sub-keymap for tools")
(keymap-set lm/leader-map "t" `("+Tools" . ,lm/leader-map-tools))
(keymap-set lm/leader-map-tools "p" 'lm/pomodoro)
(defvar lm/insert-map-special-chars (make-sparse-keymap)
  "sub-keymap for inserting special characters")
(keymap-set lm/insert-map "s" `("+Special" . ,lm/insert-map-special-chars))
(keymap-set lm/insert-map-special-chars "t" 'lm/insert-tilde)
(keymap-set lm/insert-map-special-chars "g" 'lm/insert-grave-accent)
