#+author: Leonardo Mascelli
#+title: Script System

* Description
This is the bundle of scripts i use for various tasks. The goal of this document
is to provide a general overview on how this scripts work togheter and how they
are organized.

* Powershell
Powershell is at the moment my preferred way to keep a multiplatform system of
scripts; it is already present on MS Windows and could be easily installed on
Linux even without admin rights. Therefore the strategy used to being able to
utilize powershell is to download it and add its location to the PATH
environment variable. To apply this strategy also to other softwares it is
needed a bit of organization on the location of those files.

* Folders hierarchy
The starting point of all the paths seams natural to be the home folder; then a
dedicated folder name could be easily chosen. Let it be *.lm*. All software and
various installed tools must be located inside this folder.

For the moment the folder structure could be:

~/.lm/
   ├ bin/
   ├ packages/
   ├ lsps/
   ├ tmp/

* Bootstrap
The folder structure and the powershell download and link plus the geneation of
a script for activating the environment are responsability of a system dependent
script called *bootstrap.<sh/ps1>* \\
*Note* Powershell coulds need the following libraries to work:
- libicu (or icu-libs)

** bootstrap.sh
#+begin_src shell :tangle "bootstrap.sh"
  PWSH_VERSION="7.3.5"

  # Create the folder structure
  mkdir -p ~/.lm
  mkdir -p ~/.lm/bin
  mkdir -p ~/.lm/packages
  mkdir -p ~/.lm/lsps
  mkdir -p ~/.lm/tmp

  # Clear possible previous powershell instance
  rm -rf ~/.lm/packages/pwsh

  # Download powershell
  # Try using curl
  if command -v curl &> /dev/null
  then
      curl -o ~/.lm/tmp/pwsh.tar.gz -LJO "https://github.com/PowerShell/PowerShell/releases/download/v${PWSH_VERSION}/powershell-${PWSH_VERSION}-linux-x64.tar.gz"
  else
      echo "curl not found. Trying using wget..."
      if command -v wget &> /dev/null 
      then
	  cd ~/.lm/tmp
	  wget -O "pwsh.tar.gz" "https://github.com/PowerShell/PowerShell/releases/download/v${PWSH_VERSION}/powershell-${PWSH_VERSION}-linux-x64.tar.gz"
      else
	  echo "not even wget found. Download pwsh manually"
	  echo "ABORT"
	  exit
      fi
  fi

  cd ~/.lm/packages
  mkdir -p pwsh
  cd pwsh
  tar -xf ~/.lm/tmp/pwsh.tar.gz

  ln -s ~/.lm/packages/pwsh/pwsh ~/.lm/bin/pwsh
#+end_src

** bootstrap.ps1

#+begin_src powershell :tangle "bootstrap.ps1"
  Push-Location ~
  New-Item -Type Directory -OnError Ignore -Path ".lm"
  New-Item -Type Directory -OnError Ignore -Path ".lm/bin"
  New-Item -Type Directory -OnError Ignore -Path ".lm/packages"
  New-Item -Type Directory -OnError Ignore -Path ".lm/lsps"
  New-Item -Type Directory -OnError Ignore -Path ".lm/tmp"
  Pop-Location
#+end_src

