(defun lm/insert-tilde ()                                      
  (interactive)                                 
  (insert-char (char-from-name "TILDE")))
(defun lm/insert-grave-accent ()                                      
  (interactive)                                 
  (insert-char (char-from-name "GRAVE ACCENT")))

(defun lm/get-conf-org-dir ()
  (interactive)
  (file-name-directory buffer-file-name))
